DROP TABLE IF EXISTS bookmarks;

CREATE TABLE bookmarks
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  siteName TEXT NOT NULL,
  link TEXT NOT NULL,
  rating INTEGER
);

INSERT INTO bookmarks
  (siteName, link, rating)
VALUES
  ('Google', 'https://www.google.com', 5),
  ('Yahoo', 'https://www.yahoo.com', 1),
  ('Thinkful', 'https://www.thinkful.com', 3),
  ('Reddit', 'https://www.reddit.com', 5),
  ('Twitter', 'https://www.twitter.com', 1),
  ('Facebook', 'https://www.facebook.com', 1),
  ('Twitch', 'https://www.twitch.com', 3),
  ('Stack Overflow', 'https://www.stackoverflow.com', 5),
  ('MDN', 'https://www.developer.mozilla.org', 5),
  ('NPM', 'https://www.npmjs.com', 5)
  ;